apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Monitoring
    containerImage: ghcr.io/ocp-power-automation/rsct-operator:0.0.1-alpha2
    description: Deploys the RSCT DaemonSet on all ppc64le architecture nodes of Kubernetes
      and OpenShift clusters.
    repository: https://github.com/ocp-power-automation/rsct-operator
    support: IBM
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
  name: rsct-operator.v0.0.0
  namespace: rsct-operator-system
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RSCT is the Schema for the rscts API
      displayName: RSCT
      kind: RSCT
      name: rscts.rsct.ibm.com
      version: v1alpha1
  description: "Deploys RSCT daemonset on all ppc64le architecture nodes of an Kubernetes
    and OpenShift cluster.\n\n### Prerequisite for OpenShift cluster\n- Create a catalog
    source using `quay.io/operatorhubio/catalog:latest` in `openshift-marketplace`
    namespace. \n- Use `rsct-operator-system` namespace for RSCT deployment.\n\n###
    Follow this document to deploy the RSCT operator on OpenShift cluster \n- [RSCT
    Deployment on OpenShift Clusters](https://github.com/ocp-power-automation/rsct-operator/blob/main/docs/Install.md)\n\n###
    In the Custom Resource Definition,\n- The RSCT image can be configured in the
    spec:\n```\nspec:\n  image: quay.io/powercloud/rsct-ppc64le:latest\n```\nDefault
    image is `quay.io/powercloud/rsct-ppc64le:latest`"
  displayName: RSCT Operator for IBM Power Systems
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - rsct
  - powervs
  - ibm
  - rmc
  - power
  links:
  - name: RSCT Operator
    url: https://github.com/ocp-power-automation/rsct-operator
  maintainers:
  - email: mjturek@us.ibm.com
    name: Michael Turek
  - email: varad.ahirwadkar1@ibm.com
    name: Varad Ahirwadkar
  - email: mkumatag@in.ibm.com
    name: Manjunath Kumatagi
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: IBM
  version: 0.0.0
